package com.zzh.reader.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzh.reader.model.BookMark;
import com.zzh.reader.model.Catalogue;
import com.zzh.reader.model.Book;

import com.zzh.reader.dao.BookMarkDao;
import com.zzh.reader.dao.CatalogueDao;
import com.zzh.reader.dao.BookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookMarkDaoConfig;
    private final DaoConfig catalogueDaoConfig;
    private final DaoConfig bookDaoConfig;

    private final BookMarkDao bookMarkDao;
    private final CatalogueDao catalogueDao;
    private final BookDao bookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookMarkDaoConfig = daoConfigMap.get(BookMarkDao.class).clone();
        bookMarkDaoConfig.initIdentityScope(type);

        catalogueDaoConfig = daoConfigMap.get(CatalogueDao.class).clone();
        catalogueDaoConfig.initIdentityScope(type);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        bookMarkDao = new BookMarkDao(bookMarkDaoConfig, this);
        catalogueDao = new CatalogueDao(catalogueDaoConfig, this);
        bookDao = new BookDao(bookDaoConfig, this);

        registerDao(BookMark.class, bookMarkDao);
        registerDao(Catalogue.class, catalogueDao);
        registerDao(Book.class, bookDao);
    }
    
    public void clear() {
        bookMarkDaoConfig.clearIdentityScope();
        catalogueDaoConfig.clearIdentityScope();
        bookDaoConfig.clearIdentityScope();
    }

    public BookMarkDao getBookMarkDao() {
        return bookMarkDao;
    }

    public CatalogueDao getCatalogueDao() {
        return catalogueDao;
    }

    public BookDao getBookDao() {
        return bookDao;
    }

}
