package com.zzh.reader.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zzh.reader.model.Book;
import com.zzh.reader.model.BookMark;
import com.zzh.reader.model.Catalogue;

import com.zzh.reader.dao.BookDao;
import com.zzh.reader.dao.BookMarkDao;
import com.zzh.reader.dao.CatalogueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bookDaoConfig;
    private final DaoConfig bookMarkDaoConfig;
    private final DaoConfig catalogueDaoConfig;

    private final BookDao bookDao;
    private final BookMarkDao bookMarkDao;
    private final CatalogueDao catalogueDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bookDaoConfig = daoConfigMap.get(BookDao.class).clone();
        bookDaoConfig.initIdentityScope(type);

        bookMarkDaoConfig = daoConfigMap.get(BookMarkDao.class).clone();
        bookMarkDaoConfig.initIdentityScope(type);

        catalogueDaoConfig = daoConfigMap.get(CatalogueDao.class).clone();
        catalogueDaoConfig.initIdentityScope(type);

        bookDao = new BookDao(bookDaoConfig, this);
        bookMarkDao = new BookMarkDao(bookMarkDaoConfig, this);
        catalogueDao = new CatalogueDao(catalogueDaoConfig, this);

        registerDao(Book.class, bookDao);
        registerDao(BookMark.class, bookMarkDao);
        registerDao(Catalogue.class, catalogueDao);
    }
    
    public void clear() {
        bookDaoConfig.clearIdentityScope();
        bookMarkDaoConfig.clearIdentityScope();
        catalogueDaoConfig.clearIdentityScope();
    }

    public BookDao getBookDao() {
        return bookDao;
    }

    public BookMarkDao getBookMarkDao() {
        return bookMarkDao;
    }

    public CatalogueDao getCatalogueDao() {
        return catalogueDao;
    }

}
